


FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PORT=8080 \
    MODE=api

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential curl bash \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip setuptools wheel

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY entrypoint.sh /app/entrypoint.sh
COPY src/ /app/src/
COPY models/ /app/models/
COPY mlflow.db /app/mlflow.db

RUN mkdir -p /app/out


RUN sed -i '1s/^\xEF\xBB\xBF//' /app/entrypoint.sh \
 && sed -i 's/\r$//' /app/entrypoint.sh \
 && chmod +x /app/entrypoint.sh

EXPOSE 8080

ENTRYPOINT ["bash", "/app/entrypoint.sh"]
