apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mayo-api
  namespace: '595003759214'
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      serviceAccountName: mayo-api-sa@innate-mix-432320-h1.iam.gserviceaccount.com
      timeoutSeconds: 900
      containers:
      - image: us-central1-docker.pkg.dev/innate-mix-432320-h1/docker-repo/mayo-api:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: MODE
          value: "api"
        - name: FHIR_BASE_URL
          valueFrom:
            secretKeyRef:
              name: FHIR_BASE_URL
              key: latest
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        startupProbe:
          tcpSocket:
            port: 8000
          periodSeconds: 240
          timeoutSeconds: 240
          failureThreshold: 1
  traffic:
  - latestRevision: true
    percent: 100
