{
 "title": "Mayo-Demo1 Observability",
 "refresh": "5s",
 "panels": [
  {
   "title": "API p95 Latency (seconds)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mayo_api_request_latency_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "API Requests (req/s)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(mayo_api_request_latency_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "API Errors Total (rate)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(mayo_api_errors_total[5m]))"
    }
   ]
  },
  {
   "title": "Kafka Messages (rate)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(mayo_kafka_messages_total[5m])) by (topic, direction)"
    }
   ]
  }
 ]
}