# .github/workflows/deploy-cloudrun.yml
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SKIP_MODEL_LOAD: "1"   # critical for hermetic tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run pytest
        run: pytest -q
