name: CI/CD — Mayo API to Cloud Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

env:
  REGION: ${{ secrets.GCP_REGION }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: ${{ secrets.CLOUD_RUN_SERVICE }}
  IMAGE_TAG: ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPO }}/mayo-api:${{ github.sha }}

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies for testing
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run pytest
        run: pytest -q

        env:
          SKIP_MODEL_LOAD: "1"


  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Build container & push (Cloud Build)
        run: |
          gcloud builds submit --project "${PROJECT_ID}" --tag "${IMAGE_TAG}" .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "${SERVICE}" \
            --project "${PROJECT_ID}" \
            --region "${REGION}" \
            --image "${IMAGE_TAG}" \
            --platform managed \
            --allow-unauthenticated \
            --port 8080

      - name: Output the service URL
        run: |
          URL=$(gcloud run services describe "${SERVICE}" --region "${REGION}" --format 'value(status.url)')
          echo "Deployed to: ${URL}"
